version: '3'

services:
  siteseminario:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - PROJETO=${PROJETO}
    ports:
      - "5000:80"
    links:
      - mongoteste
    depends_on:
      - "mongoteste"

  mongoteste:
    image: mongo
    volumes:
      - '../data:/data/db'
    ports:
      - "27017:27017"