version: '3'

services:
  siteseminario:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    links:
      - mongo
    depends_on:
      - "mongo"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"